/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAguaRouteImport } from './routes/_authenticated/agua'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedFitbitCallbackRouteImport } from './routes/_authenticated/fitbit-callback'
import { Route as AuthenticatedLivrosRouteImport } from './routes/_authenticated/livros'
import { Route as AuthenticatedMelhoriasRouteImport } from './routes/_authenticated/melhorias'
import { Route as AuthenticatedPrioridadesRouteImport } from './routes/_authenticated/prioridades'
import { Route as AuthenticatedRotinasRouteImport } from './routes/_authenticated/rotinas'
import { Route as AuthenticatedVocabularioRouteImport } from './routes/_authenticated/vocabulario'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAguaRoute = AuthenticatedAguaRouteImport.update({
  id: '/agua',
  path: '/agua',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFitbitCallbackRoute =
  AuthenticatedFitbitCallbackRouteImport.update({
    id: '/fitbit-callback',
    path: '/fitbit-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLivrosRoute = AuthenticatedLivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMelhoriasRoute = AuthenticatedMelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioridadesRoute =
  AuthenticatedPrioridadesRouteImport.update({
    id: '/prioridades',
    path: '/prioridades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotinasRoute = AuthenticatedRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabularioRoute =
  AuthenticatedVocabularioRouteImport.update({
    id: '/vocabulario',
    path: '/vocabulario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/agua': typeof AuthenticatedAguaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/fitbit-callback': typeof AuthenticatedFitbitCallbackRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/melhorias': typeof AuthenticatedMelhoriasRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/agua': typeof AuthenticatedAguaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/fitbit-callback': typeof AuthenticatedFitbitCallbackRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/melhorias': typeof AuthenticatedMelhoriasRoute
  '/prioridades': typeof AuthenticatedPrioridadesRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/agua': typeof AuthenticatedAguaRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/fitbit-callback': typeof AuthenticatedFitbitCallbackRoute
  '/_authenticated/livros': typeof AuthenticatedLivrosRoute
  '/_authenticated/melhorias': typeof AuthenticatedMelhoriasRoute
  '/_authenticated/prioridades': typeof AuthenticatedPrioridadesRoute
  '/_authenticated/rotinas': typeof AuthenticatedRotinasRoute
  '/_authenticated/vocabulario': typeof AuthenticatedVocabularioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/agua'
    | '/cadastros'
    | '/diario'
    | '/fitbit-callback'
    | '/livros'
    | '/melhorias'
    | '/prioridades'
    | '/rotinas'
    | '/vocabulario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agenda'
    | '/agua'
    | '/cadastros'
    | '/diario'
    | '/fitbit-callback'
    | '/livros'
    | '/melhorias'
    | '/prioridades'
    | '/rotinas'
    | '/vocabulario'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/agua'
    | '/_authenticated/cadastros'
    | '/_authenticated/diario'
    | '/_authenticated/fitbit-callback'
    | '/_authenticated/livros'
    | '/_authenticated/melhorias'
    | '/_authenticated/prioridades'
    | '/_authenticated/rotinas'
    | '/_authenticated/vocabulario'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agua': {
      id: '/_authenticated/agua'
      path: '/agua'
      fullPath: '/agua'
      preLoaderRoute: typeof AuthenticatedAguaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fitbit-callback': {
      id: '/_authenticated/fitbit-callback'
      path: '/fitbit-callback'
      fullPath: '/fitbit-callback'
      preLoaderRoute: typeof AuthenticatedFitbitCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livros': {
      id: '/_authenticated/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof AuthenticatedLivrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/melhorias': {
      id: '/_authenticated/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof AuthenticatedMelhoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prioridades': {
      id: '/_authenticated/prioridades'
      path: '/prioridades'
      fullPath: '/prioridades'
      preLoaderRoute: typeof AuthenticatedPrioridadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotinas': {
      id: '/_authenticated/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof AuthenticatedRotinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulario': {
      id: '/_authenticated/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof AuthenticatedVocabularioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAguaRoute: typeof AuthenticatedAguaRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedFitbitCallbackRoute: typeof AuthenticatedFitbitCallbackRoute
  AuthenticatedLivrosRoute: typeof AuthenticatedLivrosRoute
  AuthenticatedMelhoriasRoute: typeof AuthenticatedMelhoriasRoute
  AuthenticatedPrioridadesRoute: typeof AuthenticatedPrioridadesRoute
  AuthenticatedRotinasRoute: typeof AuthenticatedRotinasRoute
  AuthenticatedVocabularioRoute: typeof AuthenticatedVocabularioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAguaRoute: AuthenticatedAguaRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedFitbitCallbackRoute: AuthenticatedFitbitCallbackRoute,
  AuthenticatedLivrosRoute: AuthenticatedLivrosRoute,
  AuthenticatedMelhoriasRoute: AuthenticatedMelhoriasRoute,
  AuthenticatedPrioridadesRoute: AuthenticatedPrioridadesRoute,
  AuthenticatedRotinasRoute: AuthenticatedRotinasRoute,
  AuthenticatedVocabularioRoute: AuthenticatedVocabularioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
