/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedLivrosRouteImport } from './routes/_authenticated/livros'
import { Route as AuthenticatedRotinasRouteImport } from './routes/_authenticated/rotinas'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AuthenticatedVocabularioRouteImport } from './routes/_authenticated/vocabulario'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivrosRoute = AuthenticatedLivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotinasRoute = AuthenticatedRotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabularioRoute =
  AuthenticatedVocabularioRouteImport.update({
    id: '/vocabulario',
    path: '/vocabulario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/rotinas': typeof AuthenticatedRotinasRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/livros': typeof AuthenticatedLivrosRoute
  '/_authenticated/rotinas': typeof AuthenticatedRotinasRoute
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/_authenticated/vocabulario': typeof AuthenticatedVocabularioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastros'
    | '/diario'
    | '/livros'
    | '/rotinas'
    | '/saude'
    | '/vocabulario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cadastros'
    | '/diario'
    | '/livros'
    | '/rotinas'
    | '/saude'
    | '/vocabulario'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cadastros'
    | '/_authenticated/diario'
    | '/_authenticated/livros'
    | '/_authenticated/rotinas'
    | '/_authenticated/saude'
    | '/_authenticated/vocabulario'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livros': {
      id: '/_authenticated/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof AuthenticatedLivrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotinas': {
      id: '/_authenticated/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof AuthenticatedRotinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocabulario': {
      id: '/_authenticated/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof AuthenticatedVocabularioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedLivrosRoute: typeof AuthenticatedLivrosRoute
  AuthenticatedRotinasRoute: typeof AuthenticatedRotinasRoute
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedVocabularioRoute: typeof AuthenticatedVocabularioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedLivrosRoute: AuthenticatedLivrosRoute,
  AuthenticatedRotinasRoute: AuthenticatedRotinasRoute,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedVocabularioRoute: AuthenticatedVocabularioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
