// This file is automatically generated. Do not edit it directly.
// Placeholder: projeto novo ainda não tem tabelas além do Auth padrão do
// Supabase. Regenere com `npx supabase gen types typescript` quando criar as
// primeiras migrations.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
