// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      agua_registros: {
        Row: {
          id: string;
          user_id: string;
          quantidade_ml: number;
          registrado_em: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          quantidade_ml: number;
          registrado_em?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          quantidade_ml?: number;
          registrado_em?: string;
        };
        Relationships: [];
      };
      diario: {
        Row: {
          id: string;
          user_id: string;
          data: string;
          titulo: string | null;
          texto: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          data?: string;
          titulo?: string | null;
          texto: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          data?: string;
          titulo?: string | null;
          texto?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      livros: {
        Row: {
          id: string;
          user_id: string;
          titulo: string;
          autor: string | null;
          nota: number;
          comentario: string | null;
          data: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          titulo: string;
          autor?: string | null;
          nota?: number;
          comentario?: string | null;
          data?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          titulo?: string;
          autor?: string | null;
          nota?: number;
          comentario?: string | null;
          data?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      streak_estado: {
        Row: {
          id: string;
          user_id: string;
          streak_atual: number;
          recorde: number;
          congelamentos_disponiveis: number;
          ultimo_dia_processado: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          streak_atual?: number;
          recorde?: number;
          congelamentos_disponiveis?: number;
          ultimo_dia_processado?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          streak_atual?: number;
          recorde?: number;
          congelamentos_disponiveis?: number;
          ultimo_dia_processado?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      saude_checkins: {
        Row: {
          id: string;
          user_id: string;
          data: string;
          humor: number;
          energia: number | null;
          sono: number | null;
          obs: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          data?: string;
          humor: number;
          energia?: number | null;
          sono?: number | null;
          obs?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          data?: string;
          humor?: number;
          energia?: number | null;
          sono?: number | null;
          obs?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      vocabulario: {
        Row: {
          id: string;
          user_id: string;
          termo: string;
          idioma: string;
          traducao: string;
          exemplo: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          termo: string;
          idioma?: string;
          traducao: string;
          exemplo?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          termo?: string;
          idioma?: string;
          traducao?: string;
          exemplo?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      sync_streak: {
        Args: Record<PropertyKey, never>;
        Returns: {
          id: string;
          user_id: string;
          streak_atual: number;
          recorde: number;
          congelamentos_disponiveis: number;
          ultimo_dia_processado: string | null;
          updated_at: string;
        };
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
